### ISSUE TITLE
Fußnoten (nicht besonders wichtig; absolute Ausnahme)

### ISSUE THREAD

**Issue by MoHu3** [bundesverfassung-oesterreich/bv-entities#6]
Wie soll ich fußnoten darstellen? erstmal als Kommentar

**Comment by MoHu3** [comment]
okay, also in Falser I doch keine Ausnahme!! da müssten wir uns also doch nochmal etwas überlegen

**Comment by cfhaak** [comment]
@MoHu3 
Da wir Fußnoten ja nicht mimetisch darstellen müssen – also nicht mit Sternchen, Kreuzchen o.ä. – sehe ich keinen Grund, warum wir dass nicht wie alle anderen Kommentare und Anmerkungen (am Rand) auch darstellen sollen.
Frag vielleicht noch einmal bei Jörg nach, aber ich glaube nicht, dass wir das anders darstellen müssen. Sonst halt höchstens mit einem extra type-Attribut, dann wären wir auf der sicheren Seite. Aber frag wie gesagt bitte noch mal Jörg.

**Comment by cfhaak** [comment]
@MoHu3 Was genau meinst du bezüglich Falser I ?

**Comment by MoHu3** [comment]
> @MoHu3 Was genau meinst du bezüglich Falser I ?

nur, dass es da viele fußnoten gibt! (eher ein reminder für mich gewesen)

**Comment by MoHu3** [comment]
> @MoHu3 Da wir Fußnoten ja nicht mimetisch darstellen müssen – also nicht mit Sternchen, Kreuzchen o.ä. – sehe ich keinen Grund, warum wir dass nicht wie alle anderen Kommentare und Anmerkungen (am Rand) auch darstellen sollen. Frag vielleicht noch einmal bei Jörg nach, aber ich glaube nicht, dass wir das anders darstellen müssen. Sonst halt höchstens mit einem extra type-Attribut, dann wären wir auf der sicheren Seite. Aber frag wie gesagt bitte noch mal Jörg.

okay, ich spreche nächste woche mit jörg
